
"""app
Automatically generated by Colaboratory.
Original file is located at
 https://colab.research.google.com/drive/1JdRaHm60Vdar01eIsDf9nM9HI3m6cbwP
"""

from flask import Flask,render_template,request
import os
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import requests
app = Flask(__name__, template_folder="templates")
model=load_model('foodnutrition.h5')
print("Loaded model from disk")
@app.route('/')
def home():
    return render_template('home.html')

@app.route('/home')
def homepage():
    return render_template('home.html')

@app.route('/classify', methods=['GET','POST'])
def classify():
    return render_template("classify.html")

@app.route('/predict',methods=['POST','GET'])
def predict():
    if request.method=='POST':
        f=request.files['imgfile']
        basepath=os.path.dirname('__file__')
        filepath=os.path.join(basepath,"uploads",f.filename)
        f.save(filepath)
        img=image.load_img(filepath,target_size=(64,64))
        x=image.img_to_array(img)
        x=np.expand_dims(x,axis=0)
        pred=np.argmax(model.predict(x), axis=1)
        print("prediction",pred)
        index=['APPLE', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
        result=str(index[pred[0]])
        x=result
        print(x)
        result=nutrition(x)
        print(result[0]["sugar_g"])
    return render_template("result.html",showcase=(result),showcase1=(x))

def nutrition(index):
    api_url = 'https://api.calorieninjas.com/v1/nutrition?query='
    query = index
    response = requests.get(api_url + query, headers={'X-Api-Key': 'KPSGf3bVjB9MGWNDxrK1xg==tmM8Yff0j3oOEilG'})
    if response.status_code == requests.codes.ok:
        print(response.text)
    else:
        print("Error:", response.status_code, response.text)
    return response.json()['items']
if __name__ == "__main__":
    app.run()